on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name"
        required: true
        type: string

jobs:
  create-repos:
    outputs:
      app_url: ${{steps.create.outputs.url}}
    runs-on: ubuntu-latest
    steps:
    - id: create
      run: |
        echo "url=https://github.com/${{ github.repository_owner }}/${{ inputs.app_name }}" >> $GITHUB_OUTPUT
  
  seed-repos:
    needs: create-repos
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.create-repos.outputs.app_url }}"