on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Service name"
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input was: ${{ github.event.inputs.app_name }}"
